name: First Workflow 
run-name: Run on branch ${{ github.ref }}

on:
  push:
  workflow_dispatch:

jobs:
  actionOnOtherRepo:
    runs-on: ubuntu-latest
    steps:
    - uses: nelson-filipe-sousa-alpt/mynewaction@v3
  work:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ runner.os }}
    - name: Checkout
      uses: actions/checkout@v4
    - run: |
        pwd
        ls -al
    - run: echo hello world
  anotherjob:
    needs: work
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls
